# Big City Health Analysis

In [80]:
import pandas as pd

In [81]:
data = pd.read_csv('Big_Cities_Health_Data_Inventory.csv')
data.head()

,Indicator Category,Indicator,Year,Gender,Race/ Ethnicity,Value,Place,BCHC Requested Methodology,Source,Methods,Notes
0,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2013,Both,All,30.4,"Atlanta (Fulton County), GA","AIDS cases diagnosed in 2012, 2013, 2014 (as a...",Diagnoses numbers were obtained from the Georg...,NaN,NaN
1,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2012,Both,All,39.6,"Atlanta (Fulton County), GA","AIDS cases diagnosed in 2012, 2013, 2014 (as a...",Diagnoses numbers were obtained from the Georg...,NaN,NaN
2,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2011,Both,All,41.7,"Atlanta (Fulton County), GA","AIDS cases diagnosed in 2012, 2013, 2014 (as a...",Diagnoses numbers were obtained from the Georg...,NaN,NaN
3,Cancer,All Types of Cancer Mortality Rate (Age-Adjust...,2013,Male,All,195.8,"Atlanta (Fulton County), GA","2012, 2013, 2014; per 100,000 population using...","National Center for Health Statistics (NCHS), CDC",NaN,NaN
4,Cancer,All Types of Cancer Mortality Rate (Age-Adjust...,2013,Female,All,135.5,"Atlanta (Fulton County), GA","2012, 2013, 2014; per 100,000 population using...","National Center for Health Statistics (NCHS), CDC",NaN,NaN

In [82]:
data = data.drop(columns=['Source', 'Methods', 'Notes'])
data.dtypes
data['Place'] = data['Place'].astype(str)
data.dtypes

Indicator Category             object
Indicator                      object
Year                           object
Gender                         object
Race/ Ethnicity                object
Value                         float64
Place                          object
BCHC Requested Methodology     object
dtype: object

In [83]:
data['Place'].value_counts()

data['Place'] = data['Place'].str.split(',').str[0]
data['Place'] = data['Place'].str.split("(").str[0].str.strip()
data['Place'] = data['Place'].replace({'San Diego County': 'San Diego'})
data['Place'].value_counts()

Phoenix          772
Miami            707
Long Beach       667
New York         651
Denver           649
Portland         623
U.S. Total       613
Seattle          595
Las Vegas        594
Los Angeles      582
Chicago          576
Philadelphia     558
Washington       511
San Antonio      498
Boston           465
San Diego        447
Minneapolis      424
Houston          410
San Jose         407
Kansas City      383
Sacramento       367
Fort Worth       332
Atlanta          313
Cleveland        295
Detroit          289
Oakland          250
Baltimore        221
San Francisco    189
Dallas           124
Name: Place, dtype: int64

In [84]:
data.head()

,Indicator Category,Indicator,Year,Gender,Race/ Ethnicity,Value,Place,BCHC Requested Methodology
0,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2013,Both,All,30.4,Atlanta,"AIDS cases diagnosed in 2012, 2013, 2014 (as a..."
1,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2012,Both,All,39.6,Atlanta,"AIDS cases diagnosed in 2012, 2013, 2014 (as a..."
2,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2011,Both,All,41.7,Atlanta,"AIDS cases diagnosed in 2012, 2013, 2014 (as a..."
3,Cancer,All Types of Cancer Mortality Rate (Age-Adjust...,2013,Male,All,195.8,Atlanta,"2012, 2013, 2014; per 100,000 population using..."
4,Cancer,All Types of Cancer Mortality Rate (Age-Adjust...,2013,Female,All,135.5,Atlanta,"2012, 2013, 2014; per 100,000 population using..."

Purpose of this analysis is to compare health of major cities across America. What factors impact obesity and physical activity levels? Does climate play a major role or are income and education more important? This can play a role in how government should go about incentivising people to excercise more. If the issue is related to income and education, then it might be better to have more PSA's and public education towards benefits of exercise. If the issue is related to climate, it might be better to subsidize gym memberships / health foods / wellness activities

In [85]:
indicator_data = data[['Indicator Category', 'Indicator']]
indicator_data = indicator_data.groupby(['Indicator Category', 'Indicator']).first()
indicator_data

Empty DataFrame
Columns: []
Index: [(Behavioral Health/Substance Abuse, Drug Abuse-Related Hospitalization Rate (Per 100,000 people) *Comparisons of these data are difficult as definitions can vary.), (Behavioral Health/Substance Abuse, Opioid-Related Mortality Rate (Age-Adjusted; Per 100,000 people) *These data should not be compared across cities as they have different definitions), (Behavioral Health/Substance Abuse, Opioid-Related Mortality Rate (Age-Adjusted; Per 100,000 people) *These data should not be compared across cities as they have different definitions.), (Behavioral Health/Substance Abuse, Opioid-Related Mortality Rate (Crude Rate; Per 100,000 people) *These data should not be compared across cities as they have different definitions), (Behavioral Health/Substance Abuse, Percent of Adults Who Binge Drank), (Behavioral Health/Substance Abuse, Percent of High School Students Who Binge Drank), (Cancer, All Types of Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)), (Cancer, Female Breast Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)), (Cancer, Lung Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)), (Demographics, Median Household Income (Dollars)), (Demographics, Percent 18+ High School Graduates), (Demographics, Percent Below 200% Poverty Level), (Demographics, Percent Foreign Born), (Demographics, Percent of Children Living in Poverty), (Demographics, Race/Ethnicity), (Demographics, Unemployment Rate Ages 16+), (Food Safety, Rate of Laboratory Confirmed Infections Caused by Salmonella (Per 100,000 people)), (Food Safety, Rate of Laboratory Confirmed Infections Caused by Shiga Toxin-Producing E-Coli (Per 100,000 people)), (HIV/AIDS, AIDS Diagnoses Rate (Per 100,000 people)), (HIV/AIDS, HIV Diagnoses Rate (Per 100,000 people)), (HIV/AIDS, HIV-Related Mortality Rate (Age-Adjusted; Per 100,000 people)), (HIV/AIDS, Persons Living with HIV/AIDS Rate (Per 100,000 people)), (Infectious Disease, Percent of Adults Over Age 65 Who Received Pneumonia Vaccine), (Infectious Disease, Percent of Adults Who Received Seasonal Flu Shot), (Infectious Disease, Percent of Children Who Received Seasonal Flu Shot), (Infectious Disease, Pneumonia and Influenza Mortality Rate (Age-Adjusted; Per 100,000 people)), (Infectious Disease, Tuberculosis Incidence Rate (Per 100,000 people)), (Injury and Violence, Firearm Related Mortality Rate (Age-Adjusted; Per 100,000 people)), (Injury and Violence, Homicide Rate (Age-Adjusted; Per 100,000 people)), (Injury and Violence, Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people)), (Injury and Violence, Suicide Rate  (Age-Adjusted; Per 100,000 people)), (Life Expectancy and Death Rate (Overall), All-Cause Mortality Rate (Age-Adjusted; Per 100,000 people)), (Life Expectancy and Death Rate (Overall), Life Expectancy at Birth (Years)), (Maternal and Child Health, Infant Mortality Rate (Per 1,000 live births)), (Maternal and Child Health, Percent of Low Birth Weight Babies Born), (Maternal and Child Health, Percent of Mothers Under Age 20), (Nutrition, Physical Activity, & Obesity, Diabetes Mortality Rate (Age-Adjusted; Per 100,000 people)), (Nutrition, Physical Activity, & Obesity, Heart Disease Mortality Rate (Age-Adjusted; Per 100,000 people)), (Nutrition, Physical Activity, & Obesity, Percent of Adults Who Are Obese), (Nutrition, Physical Activity, & Obesity, Percent of Adults Who Meet CDC-Recommended Physical Activity Levels), (Nutrition, Physical Activity, & Obesity, Percent of High School Students Who Are Obese), (Nutrition, Physical Activity, & Obesity, Percent of High School Students Who Meet CDC-Recommended Physical Activity Levels), (Tobacco, Percent of Adults Who Currently Smoke), (Tobacco, Percent of High School Students Who Currently Smoke)]

Keep: 
(Nutrition, Physical Activity & Obesity), (Life Expectancy and Death Rate (Overall)	All-Cause Mortality Rate (Age-Adjusted; Per 100,000 people)), Demographics, Cancer

In [86]:
categories = ["Nutrition, Physical Activity, & Obesity",
              "Life Expectancy and Death Rate (Overall)",
              "Demographics", 
              "Cancer"]
data = data[data['Indicator Category'].isin(categories)]
data['Indicator Category'].value_counts()

Nutrition, Physical Activity, & Obesity     1841
Cancer                                      1432
Life Expectancy and Death Rate (Overall)     544
Demographics                                 504
Name: Indicator Category, dtype: int64

In [87]:
indicator_data = data[['Indicator Category', 'Indicator']]
indicator_data = indicator_data.groupby(['Indicator Category', 'Indicator']).first()
indicator_data

Empty DataFrame
Columns: []
Index: [(Cancer, All Types of Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)), (Cancer, Female Breast Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)), (Cancer, Lung Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)), (Demographics, Median Household Income (Dollars)), (Demographics, Percent 18+ High School Graduates), (Demographics, Percent Below 200% Poverty Level), (Demographics, Percent Foreign Born), (Demographics, Percent of Children Living in Poverty), (Demographics, Race/Ethnicity), (Demographics, Unemployment Rate Ages 16+), (Life Expectancy and Death Rate (Overall), All-Cause Mortality Rate (Age-Adjusted; Per 100,000 people)), (Life Expectancy and Death Rate (Overall), Life Expectancy at Birth (Years)), (Nutrition, Physical Activity, & Obesity, Diabetes Mortality Rate (Age-Adjusted; Per 100,000 people)), (Nutrition, Physical Activity, & Obesity, Heart Disease Mortality Rate (Age-Adjusted; Per 100,000 people)), (Nutrition, Physical Activity, & Obesity, Percent of Adults Who Are Obese), (Nutrition, Physical Activity, & Obesity, Percent of Adults Who Meet CDC-Recommended Physical Activity Levels), (Nutrition, Physical Activity, & Obesity, Percent of High School Students Who Are Obese), (Nutrition, Physical Activity, & Obesity, Percent of High School Students Who Meet CDC-Recommended Physical Activity Levels)]

In [88]:
remove_indicators = ["Female Breast Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)",
                    "Lung Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)",
                    "Percent Foreign Born",
                    "Percent of Children Living in Poverty",
                    "Race/Ethnicity",
                    "Percent Below 200% Poverty Level"]
data = data[~data['Indicator'].isin(remove_indicators)]

In [89]:
indicator_data = data[['Indicator Category', 'Indicator']]
indicator_data = indicator_data.groupby(['Indicator Category', 'Indicator']).first()
indicator_data

Empty DataFrame
Columns: []
Index: [(Cancer, All Types of Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)), (Demographics, Median Household Income (Dollars)), (Demographics, Percent 18+ High School Graduates), (Demographics, Unemployment Rate Ages 16+), (Life Expectancy and Death Rate (Overall), All-Cause Mortality Rate (Age-Adjusted; Per 100,000 people)), (Life Expectancy and Death Rate (Overall), Life Expectancy at Birth (Years)), (Nutrition, Physical Activity, & Obesity, Diabetes Mortality Rate (Age-Adjusted; Per 100,000 people)), (Nutrition, Physical Activity, & Obesity, Heart Disease Mortality Rate (Age-Adjusted; Per 100,000 people)), (Nutrition, Physical Activity, & Obesity, Percent of Adults Who Are Obese), (Nutrition, Physical Activity, & Obesity, Percent of Adults Who Meet CDC-Recommended Physical Activity Levels), (Nutrition, Physical Activity, & Obesity, Percent of High School Students Who Are Obese), (Nutrition, Physical Activity, & Obesity, Percent of High School Students Who Meet CDC-Recommended Physical Activity Levels)]

In [90]:
indicator_mapping = {
    "All Types of Cancer Mortality Rate (Age-Adjusted; Per 100,000 people)": "cancer_mortality",
    "Median Household Income (Dollars)": "median_household_income",
    "Percent 18+ High School Graduates": "hs_graduation_rate",
    "Unemployment Rate Ages 16+": "unemployment_rate",
    "All-Cause Mortality Rate (Age-Adjusted; Per 100,000 people)": "overall_mortality",
    "Life Expectancy at Birth (Years)": "life_expectancy",
    "Diabetes Mortality Rate (Age-Adjusted; Per 100,000 people)": "diabetes_mortality",
    "Heart Disease Mortality Rate (Age-Adjusted; Per 100,000 people)": "heart_disease_mortality",
    "Percent of Adults Who Are Obese": "adult_obesity_rate",
    "Percent of Adults Who Meet CDC-Recommended Physical Activity Levels": "adult_physical_activity_rate",
    "Percent of High School Students Who Are Obese": "hs_obesity_rate",
    "Percent of High School Students Who Meet CDC-Recommended Physical Activity Levels": "hs_physical_activity_rate"
}
data = data.drop(columns='Indicator Category')
data['Indicator'] = data['Indicator'].replace(indicator_mapping)

In [91]:
data['Indicator'].value_counts()

cancer_mortality                572
heart_disease_mortality         554
diabetes_mortality              538
overall_mortality               389
adult_obesity_rate              253
adult_physical_activity_rate    181
hs_physical_activity_rate       181
life_expectancy                 155
hs_obesity_rate                 134
unemployment_rate                56
median_household_income          52
hs_graduation_rate               52
Name: Indicator, dtype: int64

In [92]:
data.head()

,Indicator,Year,Gender,Race/ Ethnicity,Value,Place,BCHC Requested Methodology
3,cancer_mortality,2013,Male,All,195.8,Atlanta,"2012, 2013, 2014; per 100,000 population using..."
4,cancer_mortality,2013,Female,All,135.5,Atlanta,"2012, 2013, 2014; per 100,000 population using..."
5,cancer_mortality,2013,Both,All,159.3,Atlanta,"2012, 2013, 2014; per 100,000 population using..."
6,cancer_mortality,2012,Male,All,199.2,Atlanta,"2012, 2013, 2014; per 100,000 population using..."
7,cancer_mortality,2012,Female,All,137.6,Atlanta,"2012, 2013, 2014; per 100,000 population using..."

In [93]:
#Convert to percentages
def convert_to_percentage(indicator, value):
    if 'mortality' in indicator:
        return value / 100000
    elif 'rate' in indicator:
        return value / 100
data['Value'] = data.apply(lambda x: convert_to_percentage(x['Indicator'], x['Value']), axis = 1)

In [94]:
data = data.drop(columns='BCHC Requested Methodology')

In [95]:
data.head()

          Indicator  Year  Gender Race/ Ethnicity     Value    Place
3  cancer_mortality  2013    Male             All  0.001958  Atlanta
4  cancer_mortality  2013  Female             All  0.001355  Atlanta
5  cancer_mortality  2013    Both             All  0.001593  Atlanta
6  cancer_mortality  2012    Male             All  0.001992  Atlanta
7  cancer_mortality  2012  Female             All  0.001376  Atlanta

In [96]:
data['Race/ Ethnicity'].value_counts()

All                              1457
White                             415
Black                             412
Hispanic                          375
Asian/PI                          224
Other                             112
Native American                    69
Multiracial                        44
American Indian/Alaska Native       9
Name: Race/ Ethnicity, dtype: int64

In [97]:
#We will drop this column because data is not consistent across cities. We will only keep 'All'
data = data[data['Race/ Ethnicity'] == 'All']
data['Race/ Ethnicity'].value_counts()
data = data.drop(columns='Race/ Ethnicity')
data.head()

          Indicator  Year  Gender     Value    Place
3  cancer_mortality  2013    Male  0.001958  Atlanta
4  cancer_mortality  2013  Female  0.001355  Atlanta
5  cancer_mortality  2013    Both  0.001593  Atlanta
6  cancer_mortality  2012    Male  0.001992  Atlanta
7  cancer_mortality  2012  Female  0.001376  Atlanta

In [98]:
city_list = list(data['Place'].unique())
city_dict = dict.fromkeys(city_list, [])
print(city_dict)

{'Atlanta': [], 'Cleveland': [], 'Baltimore': [], 'Boston': [], 'Chicago': [], 'Dallas': [], 'Denver': [], 'Detroit': [], 'Fort Worth': [], 'Houston': [], 'Washington': [], 'Kansas City': [], 'Los Angeles': [], 'Las Vegas': [], 'Miami': [], 'San Jose': [], 'Minneapolis': [], 'Philadelphia': [], 'New York': [], 'Oakland': [], 'Phoenix': [], 'Portland': [], 'Sacramento': [], 'San Antonio': [], 'San Diego': [], 'San Francisco': [], 'Seattle': [], 'U.S. Total': [], 'Long Beach': []}

In [99]:
indicator_list = list(data['Indicator'].unique())
for city in city_dict.keys():
    city_dict[city] = dict.fromkeys(indicator_list, '')
print(city_dict['Atlanta'])

{'cancer_mortality': '', 'overall_mortality': '', 'diabetes_mortality': '', 'life_expectancy': '', 'heart_disease_mortality': '', 'median_household_income': '', 'hs_graduation_rate': '', 'adult_obesity_rate': '', 'adult_physical_activity_rate': '', 'unemployment_rate': '', 'hs_obesity_rate': '', 'hs_physical_activity_rate': ''}

Series([], Name: Year, dtype: int64)

Series([], Name: Year, dtype: int64)